spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${DB_NAME:charging_station}?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${DB_USER:charging}
    password: ${DB_PASSWORD:charging123}
